### PR TITLE
Reduce warnings

### PR DESCRIPTION
**Pull request by lolodomo**
"mvn clean install" is now passing.

### CODE REVIEW

**Comment by digitaldan** [comment]
Thanks !!! I have been putting this off ;-)  One note for myself is go through the handlebar templates i wrote to generate the Cluster classes and make sure they are creating properly formatted code.   You probably already saw this, but looks like there are some conflicts on this PR.

**Comment by lolodomo** [comment]
I am fixing the conflicts...

**Comment by lolodomo** [comment]
Conflicts resolved.

You have to change something in your IDE setup to avoid generating import.*. It leads to a warning.

You have now 0 warning at high level/

image

**Comment by digitaldan** [comment]
Thanks!!!!

**Pull request merged**
